// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeClubDeportivo.Contexto;

#nullable disable

namespace SistemadeClubDeportivo.Migrations
{
    [DbContext(typeof(MyContexto))]
    [Migration("20240614153015_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNaci")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomTutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCelTutor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumCelular")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fecha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyProperty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NroRecibo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaHorario")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoraHorario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCelular")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personales");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Cliente", b =>
                {
                    b.HasOne("SistemadeClubDeportivo.Models.Personal", "Personal")
                        .WithMany("Clientes")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Pago", b =>
                {
                    b.HasOne("SistemadeClubDeportivo.Models.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeClubDeportivo.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Personal", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SistemadeClubDeportivo.Models.Usuario", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
